### ISSUE TITLE
Mapper namespace support

### ISSUE THREAD

**Issue by baronnoraz** [seventh7/intellij-mybatis-plugin#41]
My apologies if I have this misconfigured or if it's a feature on a roadmap.  The plugin is wonderful, and I'd like to help make it better.

IntelliJ 14 Build #IU-139.224
MyBatis Plugin 2.32

The plugin does not appear to recognize namespaces properly.  If I define a mapper with a namespace of `Tables` and attempt to reference elements in the same file or other mapper files

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="Tables">
    <sql id="SCHEMA">${schema}.</sql>

    <sql id="TABLE_X">
        <include refid="Tables.SCHEMA"/>TABLE_X
    </sql>
</mapper>
```

IntelliJ reports an inspection error on the reference `refid="Tables.`

> Cannot resolve class or package 'Tables'
> Under Construction

Thanks.

**Comment by seventh7** [comment]
It's suggested that you reference the "SCHEMA" directly as the cascading expression is not supported

**Comment by baronnoraz** [comment]
I actually do when "SCHEMA" is in the same file.  This was the simplest way to present the problem.  The real problem is when I try to include the reference from a different XML mapper file.  The namespace reference isn't recognized in the other file.

Let's say I have the Tables.xml mapper file shown previously and q second Query.xml mapper file that wants to reference SQL fragments in the first.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="Query">
    <select id="selectTableXData">
        SELECT *
           FROM <include refid="Tables.TABLE_X"/>
    </select>
</mapper>
```

This is the proper way to reference SQL fragments from other mapper files using namespaces.  

I wasn't sure from the comment if you meant "is not supported [that's not how to do it]", "is not supported [and there is no plan to support namespaces]", or "is not supported [at this time, but that's a feature request for the future]".

I actually wanted to bring this issue up, because the `id` values in the `select` elements also report an inspection error, and I thought they might be related.

```xml
<select id="selectTableXData">
```

IntelliJ reports an inspection error on `id="selectTableXData"`

> Cannot resolve symbol 'selectTableXData'
> Under Construction

Thanks again for the wonderful plugin - again just trying to help make it better.  Trying to look over things to help contribute as well.

**Comment by seventh7** [comment]
Hi baronnoraz,

I think i misunderstood your issue. And it works well as you expected on my mac.

This is the mapper xml where the SQL fragment is defined
![source](https://cloud.githubusercontent.com/assets/3461740/6838952/73ec50a8-d39c-11e4-8d81-cf6b6ae8469a.png)

Here is the mapper xml referencing the SQL fragment defined in the previous mapper xml
![target](https://cloud.githubusercontent.com/assets/3461740/6838954/79bb6708-d39c-11e4-8b64-083c19c8e37d.png)

**Comment by baronnoraz** [comment]
That's good.  It makes me think that it's a problem of not using a fully qualified namespace.  

In my example, we're just using something like `OpsAdminMapper` instead of `com.jd.smartmaingw.dao.OpsAdminMapper` as in your example.

Also, it appears my statement of "SQL fragment" was wrong. IntelliJ does not give the inspection warning for the `id` in `resultMap` and `sql` elements but does in `select` and `update` elements.

![image](https://cloud.githubusercontent.com/assets/131762/6839093/10000722-d33a-11e4-98d6-436a7147f27f.png)

PS What version of IntelliJ are you using out of curiosity?

**Comment by seventh7** [comment]
Hi, it works well using a single word as the mapper namespace.
And the intellij version is 14.1 and built 141.177

This is the mapper xml where the SQL fragment is defined
![2015-03-26 12 58 01](https://cloud.githubusercontent.com/assets/3461740/6840675/1598808c-d3b8-11e4-8fba-85b16b5cb52e.png)

Here is the mapper xml referencing the SQL fragment defined in the previous mapper xml
![2015-03-26 12 58 20](https://cloud.githubusercontent.com/assets/3461740/6840680/214a2d18-d3b8-11e4-9623-71158ec47ae6.png)

**Comment by baronnoraz** [comment]
I was using 139.224 and upgraded to 141.177, and I'm no longer getting the inspection errors.  Something tells me my index needed to be rebuilt as I doubt the version difference truly mattered.

Regardless, it is working as expected.  My apologies for wasting your time!!! Thanks again.

**Comment by seventh7** [comment]
It's ok. Thank you for spending time on this project
