### ISSUE TITLE
2.33版本插件问题反馈

### ISSUE THREAD

**Issue by rockjava** [seventh7/intellij-mybatis-plugin#44]
最新版插件解决了java.lang.NoClassDefFoundError: org/jetbrains/generate/tostring/util/StringUtil这个问题，但新的问题来了，呵呵。
在mapper.xml文件中有跳转图标，点击能够跳转到mapper类上，但在mapper类的方法前面没有跳转图标了。

插件版本2.33 IntelliJ IDEA版本141.177

**Comment by seventh7** [comment]
这个问题一直存在着，最近很忙，没有时间去研究如何处理哈。

你可以通过这种方式来临时解决这个问题: 把XML编辑一下再通过XML里面的向上箭头跳转到Mapper. 

这样Mapper应该就会出现相应的箭头了
