### ISSUE TITLE
Result not match for select id

### ISSUE THREAD

**Issue by natros** [seventh7/intellij-mybatis-plugin#45]
Hello, 

I have this mapper 
```xml
<select id="isFoo" resultType="boolean"/>
```

for the corresponding java file
```java
boolean isFoo(int id);
```

the plugin complains about a "Result not match for select id=isFoo". the plugin is expecting
```xml
<select id="isFoo" resultType="java.lang.Boolean"/>
```

I have no problem using the FQN, but the plugin should accept the alias version of the default types

Thank you.

**Comment by seventh7** [comment]
hi, natros
both alias and qualified class name are supported. There must be some wrong if the plugin complains about that
